@TemplateAPI = http://localhost:4110/api
@Id = 1
@Message = Lorem message 2

###
GET {{TemplateAPI}}/health
###
POST {{TemplateAPI}}/chats/create
###
GET {{TemplateAPI}}/chats/{{Id}}/messages
###
POST {{TemplateAPI}}/chats/{{Id}}/messages?message={{Message}}
###
DELETE {{TemplateAPI}}/chats/{{Id}}/messages/2
###


