@TemplateAPI = http://localhost:4110/api
@Folder = proj_2
@File = proj2.txt
# @File = lorem/loremt.txt

###
GET {{TemplateAPI}}/file
###
GET {{TemplateAPI}}/file/{{Folder}}
###
GET {{TemplateAPI}}/file/{{Folder}}/{{File}}
###
