@TemplateAPI = http://localhost:4110/api

GET {{TemplateAPI}}/health

###
POST {{TemplateAPI}}/chat
Content-Type: text/plain

What's happening in the news right now?
###
POST {{TemplateAPI}}/chat
Content-Type: text/plain

Hello! Write a short poem. 
###

