export default function Home() {
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="bg-white rounded-lg shadow-md p-6">
        <h1 className="text-4xl font-bold text-gray-800 mb-4 border-b-4 border-blue-600 pb-2">
          Home
        </h1>
        <p className="text-gray-700 text-lg mb-6">
          This app provides a few features to help with brainstorming and
          coding.
        </p>
        
        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-3 border-l-4 border-blue-500 pl-3">
          Planning
        </h2>
        <p className="text-gray-600 mb-4">
          Using the Todo section, go and input a large multi-step prompt into
          the "Break" box. This will be sent to an LLM to break down into a
          smaller amount of steps for another LLM to come in and discuss all of
          those points (not yet implmented). An example has been provided below
          (yes, it was generated by an llm).
        </p>
        <p className="text-gray-600 italic bg-gray-50 p-4 rounded border-l-4 border-gray-300">
          How can I make this API more RESTful? Review the current endpoint
          structure, identify which verbs are being misused, explain proper
          resource nesting, show where HATEOAS could improve discoverability,
          and suggest versioning strategies.
        </p>
        
        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-3 border-l-4 border-blue-500 pl-3">
          Reading Code
        </h2>
        <p className="text-gray-600">
          The LLM doesn't know about it yet, but you can see the two local
          codebases I've cloned next to my app. You can explore files in the
          File tab. The project is the first select and the file is the second
          select.
        </p>
      </div>
    </div>
  );
}
